version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - devnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: devpassword
    networks:
      - devnet
      
  hourly-react-app:
    image: ghcr.io/goldenplayer5630/hourly-microservice-app:pre-release
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - devnet
    depends_on:
      - gateway

  gateway:
    image: ghcr.io/goldenplayer5630/hourly-gateway:pre-release
    container_name: gateway
    ports:
      - "5000:8080"
    environment:
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      CORS__AllowedOrigins: '["https://hourly-micro.vincentbok.nl"]'
      CORS__AllowedMethods: '["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]'
      CORS__AllowedHeaders: '["Content-Type", "Authorization"]'
      CORS__ExposedHeaders: '["X-Total-Count"]'
      CORS__AllowCredentials: "true"
      CORS__MaxAge: "3600"
      OCELOT__USER_SERVICE_HOST: userservice
      OCELOT__USER_SERVICE_PORT: 8080
      OCELOT__TIMETRACKING_SERVICE_HOST: timetracking
      OCELOT__TIMETRACKING_SERVICE_PORT: 8080
      OCELOT__GIT_SERVICE_HOST: gitservice
      OCELOT__GIT_SERVICE_PORT: 8080
      OCELOT__HTTP_TRANSPORT_SCHEME: "http"
    depends_on:
      - userservice
      - timetracking
      - gitservice
      - rabbitmq
    networks:
      - devnet

  userservice:
    image: ghcr.io/goldenplayer5630/hourly-userservice:pre-release
    container_name: userservice
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hourly-userservice;Username=admin;Password=admin123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: devuser
      RabbitMQ__Password: devpassword
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - devnet

  gitservice:
    image: ghcr.io/goldenplayer5630/hourly-gitservice:pre-release
    container_name: gitservice
    ports:
      - "5003:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hourly-gitservice;Username=admin;Password=admin123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: devuser
      RabbitMQ__Password: devpassword
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - devnet

  timetracking:
    image: ghcr.io/goldenplayer5630/hourly-timetracking:pre-release
    container_name: timetracking
    ports:
      - "5002:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hourly-timetrackingservice;Username=admin;Password=admin123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: devuser
      RabbitMQ__Password: devpassword
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - devnet

volumes:
  postgres_data:

networks:
  devnet:

