version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - devnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: devpassword
    networks:
      - devnet

  gateway:
    image: hourly-gateway:latest
    container_name: gateway
    build:
      context: .
      dockerfile: Hourly.Gateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      OCELOT__USER_SERVICE_HOST: userservice
      OCELOT__USER_SERVICE_PORT: 8080
      OCELOT__TIMETRACKING_SERVICE_HOST: timetracking
      OCELOT__TIMETRACKING_SERVICE_PORT: 8080
      OCELOT__GIT_SERVICE_HOST: gitservice
      OCELOT__GIT_SERVICE_PORT: 8080
      OCELOT__HTTP_TRANSPORT_SCHEME: "http"
    depends_on:
      - userservice
      - timetracking
      - gitservice
      - rabbitmq
    networks:
      - devnet

  userservice:
    image: hourly-userservice:latest
    container_name: userservice
    build:
      context: .
      dockerfile: Hourly.UserService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hourly-userservice;Username=admin;Password=admin123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: devuser
      RabbitMQ__Password: devpassword
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - devnet

  gitservice:
    image: hourly-gitservice:latest
    container_name: gitservice
    build:
      context: .
      dockerfile: Hourly.GitService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hourly-gitservice;Username=admin;Password=admin123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: devuser
      RabbitMQ__Password: devpassword
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - devnet

  timetracking:
    image: hourly-timetracking:latest
    container_name: timetracking
    build:
      context: .
      dockerfile: Hourly.TimeTrackingService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hourly-timetrackingservice;Username=admin;Password=admin123"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: devuser
      RabbitMQ__Password: devpassword
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - devnet

volumes:
  postgres_data:

networks:
  devnet:
